//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CochesCutresApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int CompraId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TipoID { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> VehiculoID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual TipoCompraVenta TipoCompraVenta { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
